export const seekers = [
  {
    id: 1,
    ad_type: "job",
    title: "باحث عن عمل اداري",
    job_type: "full_time",
    governorate: "دمشق",
    location: "الميدان",
    education: "دبلوم اداره مكتبية",
    experience: "خبرة سنه واحدة",
    skills: "مهارات تواصل ممتازة",
    description: "..............................",
    work_hours: "صباحي",
    phone_number: "1234355353",
    email: "test@gmail.com",
    type: "search_for_work",
    job_title: "مساعد اداري",
    images: [
      "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: 2,
    ad_type: "job",
    title: "باحث عن عمل محاسب",
    job_type: "full_time",
    governorate: "حلب",
    location: "السليمانية",
    education: "بكالوريوس محاسبة",
    experience: "3 سنوات",
    skills: "إتقان برامج المحاسبة, Excel",
    description: "أبحث عن فرصة عمل في مجال المحاسبة",
    work_hours: "صباحي أو مسائي",
    phone_number: "0912345678",
    email: "accountant.seeker@gmail.com",
    type: "search_for_work",
    job_title: "محاسب",
  },
  {
    id: 3,
    ad_type: "job",
    title: "باحث عن عمل في مجال المبيعات",
    job_type: "part_time",
    governorate: "حمص",
    location: "الكرامة",
    education: "ثانوية عامة",
    experience: "سنتين في المبيعات",
    skills: "مهارات تواصل, القدرة على الإقناع",
    description: "أبحث عن عمل في مجال المبيعات مع إمكانية التنقل",
    work_hours: "مرن",
    phone_number: "0934567890",
    email: "sales.seeker@gmail.com",
    type: "search_for_work",
    job_title: "مندوب مبيعات",
  },
  {
    id: 4,
    ad_type: "job",
    title: "مهندس مدني يبحث عن عمل",
    job_type: "full_time",
    governorate: "دمشق",
    location: "المزة",
    education: "إجازة في الهندسة المدنية",
    experience: "5 سنوات",
    skills: "AutoCAD, إدارة المشاريع",
    description: "أبحث عن فرصة عمل في مجال الهندسة المدنية",
    work_hours: "صباحي",
    phone_number: "0945678901",
    email: "civil.engineer@gmail.com",
    type: "search_for_work",
    job_title: "مهندس مدني",
  },
  {
    id: 5,
    ad_type: "job",
    title: "باحثة عن عمل كمدرسة لغة انكليزية",
    job_type: "part_time",
    governorate: "اللاذقية",
    location: "الجامعة",
    education: "إجازة في اللغة الانكليزية",
    experience: "4 سنوات تدريس",
    skills: "إتقان اللغة, مهارات تدريس",
    description: "أبحث عن عمل كمدرسة لغة انكليزية في معهد أو مدرسة",
    work_hours: "مسائي",
    phone_number: "0956789012",
    email: "english.teacher@gmail.com",
    type: "search_for_work",
    job_title: "مدرسة لغة انكليزية",
  },
  {
    id: 6,
    ad_type: "job",
    title: "باحث عن عمل سائق",
    job_type: "full_time",
    governorate: "دمشق",
    location: "ركن الدين",
    education: "ثانوية عامة",
    experience: "7 سنوات قيادة",
    skills: "رخصة قيادة, معرفة بأحياء المدينة",
    description: "أبحث عن عمل سائق خاص أو توصيل",
    work_hours: "مرن",
    phone_number: "0967890123",
    email: "driver.seeker@gmail.com",
    type: "search_for_work",
    job_title: "سائق",
  },
  {
    id: 7,
    ad_type: "job",
    title: "طبيب أسنان يبحث عن عمل",
    job_type: "full_time",
    governorate: "حماة",
    location: "المركز",
    education: "دكتوراه في طب الأسنان",
    experience: "3 سنوات",
    skills: "التركيبات, الحشوات, قلع الأسنان",
    description: "أبحث عن عمل في عيادة أسنان",
    work_hours: "صباحي ومسائي",
    phone_number: "0978901234",
    email: "dentist.seeker@gmail.com",
    type: "search_for_work",
    job_title: "طبيب أسنان",
  },
  {
    id: 8,
    ad_type: "job",
    title: "مصمم جرافيك يبحث عن عمل",
    job_type: "remote",
    governorate: "كل المحافظات",
    location: "عن بعد",
    education: "دبلوم تصميم جرافيك",
    experience: "4 سنوات",
    skills: "Photoshop, Illustrator, InDesign",
    description: "أبحث عن عمل كمصمم جرافيك عن بعد",
    work_hours: "مرن",
    phone_number: "0989012345",
    email: "designer.seeker@gmail.com",
    type: "search_for_work",
    job_title: "مصمم جرافيك",
  },
  {
    id: 9,
    ad_type: "job",
    title: "ممرضة تبحث عن عمل",
    job_type: "full_time",
    governorate: "درعا",
    location: "المركز",
    education: "شهادة تمريض",
    experience: "5 سنوات",
    skills: "العناية بالمرضى, الحقن, الطوارئ",
    description: "أبحث عن عمل في مستشفى أو عيادة",
    work_hours: "نوبات",
    phone_number: "0990123456",
    email: "nurse.seeker@gmail.com",
    type: "search_for_work",
    job_title: "ممرضة",
  },
  {
    id: 10,
    ad_type: "job",
    title: "باحث عن عمل مدخل بيانات",
    job_type: "part_time",
    governorate: "دمشق",
    location: "القصاع",
    education: "ثانوية عامة",
    experience: "سنة واحدة",
    skills: "سرعة الطباعة, إتقان الحاسوب",
    description: "أبحث عن عمل مدخل بيانات بدوام جزئي",
    work_hours: "مسائي",
    phone_number: "0911234567",
    email: "dataentry.seeker@gmail.com",
    type: "search_for_work",
    job_title: "مدخل بيانات",
  },
  {
    id: 11,
    ad_type: "job",
    title: "مهندس كهرباء يبحث عن عمل",
    job_type: "full_time",
    governorate: "حلب",
    location: "الشيخ مقصود",
    education: "إجازة في الهندسة الكهربائية",
    experience: "6 سنوات",
    skills: "تصميم الشبكات الكهربائية, الصيانة",
    description: "أبحث عن عمل في مجال الهندسة الكهربائية",
    work_hours: "صباحي",
    phone_number: "0922345678",
    email: "electrical.engineer@gmail.com",
    type: "search_for_work",
    job_title: "مهندس كهرباء",
  },
  {
    id: 12,
    ad_type: "job",
    title: "باحث عن عمل في مجال البيع",
    job_type: "full_time",
    governorate: "دمشق",
    location: "الحمراء",
    education: "ثانوية تجارية",
    experience: "3 سنوات في البيع",
    skills: "مهارات بيع, خدمة الزبائن",
    description: "أبحث عن عمل بائع في محل تجاري",
    work_hours: "صباحي ومسائي",
    phone_number: "0933456789",
    email: "salesman.seeker@gmail.com",
    type: "search_for_work",
    job_title: "بائع",
  },
  {
    id: 13,
    ad_type: "job",
    title: "خباز يبحث عن عمل",
    job_type: "full_time",
    governorate: "حمص",
    location: "الوعر",
    education: "دبلوم صناعي",
    experience: "8 سنوات",
    skills: "صناعة الخبز, إدارة المخبز",
    description: "أبحث عن عمل في مخبز آلي أو تقليدي",
    work_hours: "صباحي باكر",
    phone_number: "0944567890",
    email: "baker.seeker@gmail.com",
    type: "search_for_work",
    job_title: "خباز",
  },
  {
    id: 14,
    ad_type: "job",
    title: "مترجم يبحث عن عمل",
    job_type: "remote",
    governorate: "كل المحافظات",
    location: "عن بعد",
    education: "إجازة في الترجمة",
    experience: "5 سنوات",
    skills: "الترجمة من والى العربية, الإنجليزية والفرنسية",
    description: "أبحث عن مشاريع ترجمة عن بعد",
    work_hours: "مرن",
    phone_number: "0955678901",
    email: "translator.seeker@gmail.com",
    type: "search_for_work",
    job_title: "مترجم",
  },
  {
    id: 15,
    ad_type: "job",
    title: "ميكانيكي سيارات يبحث عن عمل",
    job_type: "full_time",
    governorate: "دمشق",
    location: "الميدان",
    education: "دبلوم ميكانيك سيارات",
    experience: "10 سنوات",
    skills: "صيانة السيارات, الكهرباء, الميكانيك",
    description: "أبحث عن عمل في ورشة سيارات",
    work_hours: "صباحي ومسائي",
    phone_number: "0966789012",
    email: "mechanic.seeker@gmail.com",
    type: "search_for_work",
    job_title: "ميكانيكي سيارات",
  },
  {
    id: 16,
    ad_type: "job",
    title: "مسوق إلكتروني يبحث عن عمل",
    job_type: "full_time",
    governorate: "حلب",
    location: "العزيزية",
    education: "بكالوريوس تسويق",
    experience: "4 سنوات",
    skills: "التسويق عبر السوشيال ميديا, إدارة الحملات",
    description: "أبحث عن عمل في مجال التسويق الإلكتروني",
    work_hours: "صباحي",
    phone_number: "0977890123",
    email: "marketer.seeker@gmail.com",
    type: "search_for_work",
    job_title: "مسوق إلكتروني",
  },
  {
    id: 17,
    ad_type: "job",
    title: "عامل بناء يبحث عن عمل",
    job_type: "full_time",
    governorate: "دمشق",
    location: "كفر سوسة",
    education: "لا يشترط",
    experience: "12 سنة",
    skills: "البناء, التلييس, البلاط",
    description: "أبحث عن عمل في مواقع البناء",
    work_hours: "صباحي",
    phone_number: "0988901234",
    email: "builder.seeker@gmail.com",
    type: "search_for_work",
    job_title: "عامل بناء",
  },
  {
    id: 18,
    ad_type: "job",
    title: "صيدلاني يبحث عن عمل",
    job_type: "full_time",
    governorate: "حمص",
    location: "الخالدية",
    education: "إجازة في الصيدلة",
    experience: "3 سنوات",
    skills: "إدارة الصيدلية, صرف الوصفات",
    description: "أبحث عن عمل في صيدلية",
    work_hours: "نوبات",
    phone_number: "0999012345",
    email: "pharmacist.seeker@gmail.com",
    type: "search_for_work",
    job_title: "صيدلاني",
  },
  {
    id: 19,
    ad_type: "job",
    title: "مدير مبيعات يبحث عن عمل",
    job_type: "full_time",
    governorate: "دمشق",
    location: "أبو رمانة",
    education: "ماجستير إدارة أعمال",
    experience: "8 سنوات",
    skills: "إدارة الفرق, التخطيط الاستراتيجي",
    description: "أبحث عن عمل في إدارة المبيعات",
    work_hours: "صباحي",
    phone_number: "0910123456",
    email: "salesmanager.seeker@gmail.com",
    type: "search_for_work",
    job_title: "مدير مبيعات",
  },
  {
    id: 20,
    ad_type: "job",
    title: "مدرس رياضيات يبحث عن عمل",
    job_type: "part_time",
    governorate: "اللاذقية",
    location: "الجامعة",
    education: "إجازة في الرياضيات",
    experience: "7 سنوات تدريس",
    skills: "شرح المنهاج, حل المسائل",
    description: "أبحث عن عمل مدرس رياضيات بدوام جزئي",
    work_hours: "مسائي",
    phone_number: "0921234567",
    email: "math.teacher@gmail.com",
    type: "search_for_work",
    job_title: "مدرس رياضيات",
  },
  {
    id: 21,
    ad_type: "job",
    title: "مدير مطعم يبحث عن عمل",
    job_type: "full_time",
    governorate: "دمشق",
    location: "الشعلان",
    education: "دبلوم إدارة مطاعم",
    experience: "6 سنوات",
    skills: "إدارة المطعم, خدمة الزبائن",
    description: "أبحث عن عمل مدير مطعم",
    work_hours: "صباحي ومسائي",
    phone_number: "0932345678",
    email: "restaurant.manager@gmail.com",
    type: "search_for_work",
    job_title: "مدير مطعم",
  },
];


export const getSeeking = (id) => {
  return seekers?.find((e) => e.id === parseInt(id));
};
