export const vacancies = [
  {
    id: 1,
    ad_type: "job",
    title: "مندوب مبيعات - دوام كامل",
    job_type: "full_time",
    governorate: "دمشق",
    location: "البرامكة",
    salary: "2 مليون",
    education: "ثانوية عامة على الاقل",
    experience: "سنة على الاقل",
    skills: "مهارات تواصل ممتازة, القدرة على العمل تحت الضغط",
    description: "مطلوب مندوب مبيعات لشركة مواد غذائية",
    work_hours: "8 ساعات يوميا",
    start_date: "18/5/2025",
    phone_number: "12334553636",
    email: "sales1@gmail.com",
    type: "job_vacancy",
    job_title: "مندوب مبيعات",
    images: [
      "https://images.unsplash.com/photo-1527838832700-5059252407fa?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1492571350019-22de08371fd3?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1533929736458-ca588d08c8be?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1486299267070-83823f5448dd?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: 2,
    ad_type: "job",
    title: "مبرمج ويب - دوام جزئي",
    job_type: "part_time",
    governorate: "حلب",
    location: "السليمانية",
    salary: "3.5 مليون",
    education: "شهادة جامعية في المعلوماتية",
    experience: "3 سنوات على الأقل",
    skills: "HTML, CSS, JavaScript, React",
    description: "مطلوب مبرمج ويب لشركة ناشئة",
    work_hours: "5 ساعات يوميا",
    start_date: "1/6/2025",
    phone_number: "0987654321",
    email: "webdev@company.com",
    type: "job_vacancy",
    job_title: "مبرمج ويب",
  },
  {
    id: 3,
    ad_type: "job",
    title: "مدرس لغة انكليزية",
    job_type: "full_time",
    governorate: "حمص",
    location: "الكرامة",
    salary: "2.8 مليون",
    education: "إجازة في اللغة الانكليزية",
    experience: "سنتين على الأقل",
    skills: "إتقان اللغة الانكليزية, مهارات تدريس",
    description: "مطلوب مدرس لغة انكليزية لمعهد تعليمي",
    work_hours: "6 ساعات يوميا",
    start_date: "15/5/2025",
    phone_number: "0912345678",
    email: "english@institute.edu",
    type: "job_vacancy",
    job_title: "مدرس لغة انكليزية",
  },
  {
    id: 4,
    ad_type: "job",
    title: "مهندس مدني",
    job_type: "full_time",
    governorate: "دمشق",
    location: "المزة",
    salary: "5 مليون",
    education: "إجازة في الهندسة المدنية",
    experience: "5 سنوات على الأقل",
    skills: "AutoCAD, إدارة المشاريع",
    description: "مطلوب مهندس مدني لشركة مقاولات",
    work_hours: "8 ساعات يوميا",
    start_date: "1/7/2025",
    phone_number: "0933333333",
    email: "civil@engineering.com",
    type: "job_vacancy",
    job_title: "مهندس مدني",
  },
  {
    id: 5,
    ad_type: "job",
    title: "محاسب",
    job_type: "full_time",
    governorate: "اللاذقية",
    location: "الجامعة",
    salary: "3 مليون",
    education: "إجازة في المحاسبة",
    experience: "سنتين على الأقل",
    skills: "إتقان برامج المحاسبة, Excel",
    description: "مطلوب محاسب لشركة تجارية",
    work_hours: "8 ساعات يوميا",
    start_date: "20/5/2025",
    phone_number: "0944444444",
    email: "accountant@company.com",
    type: "job_vacancy",
    job_title: "محاسب",
  },
  {
    id: 6,
    ad_type: "job",
    title: "سائق توصيل",
    job_type: "part_time",
    governorate: "دمشق",
    location: "ركن الدين",
    salary: "1.5 مليون",
    education: "لا يشترط",
    experience: "سنة على الأقل",
    skills: "رخصة قيادة, معرفة بأحياء المدينة",
    description: "مطلوب سائق توصيل لمطعم",
    work_hours: "6 ساعات يوميا",
    start_date: "10/5/2025",
    phone_number: "0955555555",
    email: "delivery@restaurant.com",
    type: "job_vacancy",
    job_title: "سائق توصيل",
  },
  {
    id: 7,
    ad_type: "job",
    title: "طبيب أسنان",
    job_type: "full_time",
    governorate: "حماة",
    location: "المركز",
    salary: "8 مليون",
    education: "دكتوراه في طب الأسنان",
    experience: "3 سنوات على الأقل",
    skills: "خبرة في التركيبات والتقويم",
    description: "مطلوب طبيب أسنان لعيادة خاصة",
    work_hours: "7 ساعات يوميا",
    start_date: "1/6/2025",
    phone_number: "0966666666",
    email: "dentist@clinic.com",
    type: "job_vacancy",
    job_title: "طبيب أسنان",
  },
  {
    id: 8,
    ad_type: "job",
    title: "مصمم جرافيك",
    job_type: "remote",
    governorate: "كل المحافظات",
    location: "عن بعد",
    salary: "4 مليون",
    education: "شهادة في التصميم الجرافيكي",
    experience: "سنتين على الأقل",
    skills: "Photoshop, Illustrator",
    description: "مطلوب مصمم جرافيك لشركة إعلانية",
    work_hours: "مرن",
    start_date: "15/5/2025",
    phone_number: "0977777777",
    email: "design@advertising.com",
    type: "job_vacancy",
    job_title: "مصمم جرافيك",
  },
  {
    id: 9,
    ad_type: "job",
    title: "ممرضة",
    job_type: "full_time",
    governorate: "درعا",
    location: "المركز",
    salary: "3 مليون",
    education: "شهادة تمريض",
    experience: "سنة على الأقل",
    skills: "خبرة في الطوارئ",
    description: "مطلوب ممرضة لمستشفى خاص",
    work_hours: "8 ساعات يوميا",
    start_date: "1/6/2025",
    phone_number: "0988888888",
    email: "nurse@hospital.com",
    type: "job_vacancy",
    job_title: "ممرضة",
  },
  {
    id: 10,
    ad_type: "job",
    title: "مدخل بيانات",
    job_type: "part_time",
    governorate: "دمشق",
    location: "القصاع",
    salary: "1.8 مليون",
    education: "ثانوية عامة على الأقل",
    experience: "لا يشترط",
    skills: "سرعة الطباعة, إتقان الحاسوب",
    description: "مطلوب مدخل بيانات لشركة تجارية",
    work_hours: "5 ساعات يوميا",
    start_date: "20/5/2025",
    phone_number: "0999999999",
    email: "dataentry@company.com",
    type: "job_vacancy",
    job_title: "مدخل بيانات",
  },
  {
    id: 11,
    ad_type: "job",
    title: "مهندس كهرباء",
    job_type: "full_time",
    governorate: "حلب",
    location: "الشيخ مقصود",
    salary: "4.5 مليون",
    education: "إجازة في الهندسة الكهربائية",
    experience: "4 سنوات على الأقل",
    skills: "خبرة في التصميم الكهربائي",
    description: "مطلوب مهندس كهرباء لمشاريع إنشائية",
    work_hours: "8 ساعات يوميا",
    start_date: "1/7/2025",
    phone_number: "0911111111",
    email: "electrical@engineering.com",
    type: "job_vacancy",
    job_title: "مهندس كهرباء",
  },
  {
    id: 12,
    ad_type: "job",
    title: "بائع في محل ألبسة",
    job_type: "full_time",
    governorate: "دمشق",
    location: "الحمراء",
    salary: "1.8 مليون",
    education: "ثانوية عامة على الأقل",
    experience: "سنة على الأقل",
    skills: "مهارات بيع, حسن المظهر",
    description: "مطلوب بائع لمحل ألبسة رجالية",
    work_hours: "9 ساعات يوميا",
    start_date: "15/5/2025",
    phone_number: "0922222222",
    email: "sales@clothing.com",
    type: "job_vacancy",
    job_title: "بائع",
  },
  {
    id: 13,
    ad_type: "job",
    title: "خباز",
    job_type: "full_time",
    governorate: "حمص",
    location: "الوعر",
    salary: "2.2 مليون",
    education: "لا يشترط",
    experience: "سنتين على الأقل",
    skills: "خبرة في صناعة الخبز",
    description: "مطلوب خباز لمخبز آلي",
    work_hours: "10 ساعات يوميا",
    start_date: "1/6/2025",
    phone_number: "0933333333",
    email: "baker@bakery.com",
    type: "job_vacancy",
    job_title: "خباز",
  },
  {
    id: 14,
    ad_type: "job",
    title: "مترجم",
    job_type: "remote",
    governorate: "كل المحافظات",
    location: "عن بعد",
    salary: "3 مليون",
    education: "إجازة في اللغة الانكليزية أو الفرنسية",
    experience: "سنتين على الأقل",
    skills: "إتقان الترجمة من والى العربية",
    description: "مطلوب مترجم لمشاريع ترجمة",
    work_hours: "مرن",
    start_date: "15/5/2025",
    phone_number: "0944444444",
    email: "translator@company.com",
    type: "job_vacancy",
    job_title: "مترجم",
  },
  {
    id: 15,
    ad_type: "job",
    title: "ميكانيكي سيارات",
    job_type: "full_time",
    governorate: "دمشق",
    location: "الميدان",
    salary: "2.5 مليون",
    education: "لا يشترط",
    experience: "3 سنوات على الأقل",
    skills: "خبرة في صيانة السيارات",
    description: "مطلوب ميكانيكي لورشة سيارات",
    work_hours: "8 ساعات يوميا",
    start_date: "20/5/2025",
    phone_number: "0955555555",
    email: "mechanic@garage.com",
    type: "job_vacancy",
    job_title: "ميكانيكي سيارات",
  },
  {
    id: 16,
    ad_type: "job",
    title: "مسوق إلكتروني",
    job_type: "full_time",
    governorate: "حلب",
    location: "العزيزية",
    salary: "3.2 مليون",
    education: "شهادة في التسويق أو مجال مشابه",
    experience: "سنتين على الأقل",
    skills: "خبرة في التسويق عبر السوشيال ميديا",
    description: "مطلوب مسوق إلكتروني لشركة تجارية",
    work_hours: "8 ساعات يوميا",
    start_date: "1/6/2025",
    phone_number: "0966666666",
    email: "marketing@company.com",
    type: "job_vacancy",
    job_title: "مسوق إلكتروني",
  },
  {
    id: 17,
    ad_type: "job",
    title: "عامل بناء",
    job_type: "full_time",
    governorate: "دمشق",
    location: "كفر سوسة",
    salary: "2 مليون",
    education: "لا يشترط",
    experience: "سنة على الأقل",
    skills: "خبرة في أعمال البناء",
    description: "مطلوب عامل بناء لموقع إنشائي",
    work_hours: "8 ساعات يوميا",
    start_date: "10/5/2025",
    phone_number: "0977777777",
    email: "construction@company.com",
    type: "job_vacancy",
    job_title: "عامل بناء",
  },
  {
    id: 18,
    ad_type: "job",
    title: "صيدلاني",
    job_type: "full_time",
    governorate: "حمص",
    location: "الخالدية",
    salary: "4 مليون",
    education: "إجازة في الصيدلة",
    experience: "سنتين على الأقل",
    skills: "خبرة في الصيدليات",
    description: "مطلوب صيدلاني لصيدلية",
    work_hours: "8 ساعات يوميا",
    start_date: "15/5/2025",
    phone_number: "0988888888",
    email: "pharmacist@pharmacy.com",
    type: "job_vacancy",
    job_title: "صيدلاني",
  },
  {
    id: 19,
    ad_type: "job",
    title: "مشرف مبيعات",
    job_type: "full_time",
    governorate: "دمشق",
    location: "أبو رمانة",
    salary: "4.5 مليون",
    education: "شهادة جامعية في إدارة الأعمال",
    experience: "4 سنوات على الأقل",
    skills: "قيادة فريق, مهارات إدارية",
    description: "مطلوب مشرف مبيعات لشركة تجارية",
    work_hours: "8 ساعات يوميا",
    start_date: "1/6/2025",
    phone_number: "0999999999",
    email: "salesmanager@company.com",
    type: "job_vacancy",
    job_title: "مشرف مبيعات",
  },
  {
    id: 20,
    ad_type: "job",
    title: "مدرس رياضيات",
    job_type: "part_time",
    governorate: "اللاذقية",
    location: "الجامعة",
    salary: "2.5 مليون",
    education: "إجازة في الرياضيات",
    experience: "سنتين على الأقل",
    skills: "خبرة في التدريس",
    description: "مطلوب مدرس رياضيات لمعاهد تعليمية",
    work_hours: "4 ساعات يوميا",
    start_date: "20/5/2025",
    phone_number: "0910101010",
    email: "math@institute.edu",
    type: "job_vacancy",
    job_title: "مدرس رياضيات",
  },
  {
    id: 21,
    ad_type: "job",
    title: "مشرف مطعم",
    job_type: "full_time",
    governorate: "دمشق",
    location: "الشعلان",
    salary: "3 مليون",
    education: "شهادة في إدارة المطاعم",
    experience: "3 سنوات على الأقل",
    skills: "إدارة الفريق, خدمة الزبائن",
    description: "مطلوب مشرف مطعم لمطعم فاخر",
    work_hours: "9 ساعات يوميا",
    start_date: "1/6/2025",
    phone_number: "0920202020",
    email: "restaurant@manager.com",
    type: "job_vacancy",
    job_title: "مشرف مطعم",
  },
];



export const getVacancy = (id) => {
  return vacancies?.find((e) => e.id === parseInt(id));
};


